
#    KEY            [0]            [1]      [2]                   [3]          [4]
# CNJ3	:        COD_RAMO	RAMO_JUSTICA	SIGLA_JUSTICA	SIGLA_TRIBUNAL	NOME_TRIBUNAL


dic_cnj3_tribunal = {
    '100' : ( '1',  'Supremo Tribunal Federal',  'STF',  'STF',  'Supremo Tribunal Federal'  ),
    '200' : ( '2',  'Conselho Nacional de Justiça',  'CNJ',  'CNJ',  'Conselho Nacional de Justiça'  ),
    '300' : ( '3',  'Superior Tribunal de Justiça',  'STJ',  'STJ',  'Superior Tribunal de Justiça'  ),
    '400' : ( '4',  'Justiça Federal',  'TRF',  'TRF',  'Justiça Federal'  ),
    '401' : ( '4',  'Justiça Federal',  'TRF',  'TRF1',  'TRF da 1a Região'  ),
    '402' : ( '4',  'Justiça Federal',  'TRF',  'TRF2',  'TRF da 2a Região'  ),
    '403' : ( '4',  'Justiça Federal',  'TRF',  'TRF3',  'TRF da 3a Região'  ),
    '404' : ( '4',  'Justiça Federal',  'TRF',  'TRF4',  'TRF da 4a Região'  ),
    '405' : ( '4',  'Justiça Federal',  'TRF',  'TRF5',  'TRF da 5a Região'  ),
    '500' : ( '5',  'Justiça do Trabalho',  'TRT',  'TST',  'Tribunal Superior do Trabalho'  ),
    '501' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT1',  'Tribunal Regional do Trabalho da 1ª Região'  ),
    '502' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT2',  'Tribunal Regional do Trabalho da 2ª Região'  ),
    '503' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT3',  'Tribunal Regional do Trabalho da 3ª Região'  ),
    '504' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT4',  'Tribunal Regional do Trabalho da 4ª Região'  ),
    '505' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT5',  'Tribunal Regional do Trabalho da 5ª Região'  ),
    '506' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT6',  'Tribunal Regional do Trabalho da 6ª Região'  ),
    '507' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT7',  'Tribunal Regional do Trabalho da 7ª Região'  ),
    '508' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT8',  'Tribunal Regional do Trabalho da 8ª Região'  ),
    '509' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT9',  'Tribunal Regional do Trabalho da 9ª Região'  ),
    '510' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT10',  'Tribunal Regional do Trabalho da 10ª Região'  ),
    '511' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT11',  'Tribunal Regional do Trabalho da 11ª Região'  ),
    '512' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT12',  'Tribunal Regional do Trabalho da 12ª Região'  ),
    '513' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT13',  'Tribunal Regional do Trabalho da 13ª Região'  ),
    '514' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT14',  'Tribunal Regional do Trabalho da 14ª Região'  ),
    '515' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT15',  'Tribunal Regional do Trabalho da 15ª Região'  ),
    '516' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT16',  'Tribunal Regional do Trabalho da 16ª Região'  ),
    '517' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT17',  'Tribunal Regional do Trabalho da 17ª Região'  ),
    '518' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT18',  'Tribunal Regional do Trabalho da 18ª Região'  ),
    '519' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT19',  'Tribunal Regional do Trabalho da 19ª Região'  ),
    '520' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT20',  'Tribunal Regional do Trabalho da 20ª Região'  ),
    '521' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT21',  'Tribunal Regional do Trabalho da 21ª Região'  ),
    '522' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT22',  'Tribunal Regional do Trabalho da 22ª Região'  ),
    '523' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT23',  'Tribunal Regional do Trabalho da 23ª Região'  ),
    '524' : ( '5',  'Justiça do Trabalho',  'TRT',  'TRT24',  'Tribunal Regional do Trabalho da 24ª Região'  ),
    '590' : ( '5',  'Justiça do Trabalho',  'TRT',  'CSJT',  'Conselho Superior da Justiça do Trabalho'  ),
    '601' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-AC',  'Tribunal Regional Eleitoral do Estado do Acre'  ),
    '602' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-AL',  'Tribunal Regional Eleitoral do Estado de Alagoas'  ),
    '603' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-AP',  'Tribunal Regional Eleitoral do Estado do Amazonas'  ),
    '604' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-AM',  'Tribunal Regional Eleitoral do Estado do Amapá'  ),
    '605' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-BA',  'Tribunal Regional Eleitoral do Estado da Bahia'  ),
    '606' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-CE',  'Tribunal Regional Eleitoral do Estado do Ceará'  ),
    '607' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-DF',  'Tribunal Regional Eleitoral do Distrito Federal '  ),
    '608' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-ES',  'Tribunal Regional Eleitoral do Estado do Espírito Santo'  ),
    '609' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-GO',  'Tribunal Regional Eleitoral do Estado de Goiás'  ),
    '610' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-MA',  'Tribunal Regional Eleitoral do Estado do Maranhão'  ),
    '611' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-MT',  'Tribunal Regional Eleitoral do Estado de Minas Gerais'  ),
    '612' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-MS',  'Tribunal Regional Eleitoral do Estado de Mato Grosso do Sul'  ),
    '613' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-MG',  'Tribunal Regional Eleitoral do Estado de Mato Grosso'  ),
    '614' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-PA',  'Tribunal Regional Eleitoral do Estado do Pará'  ),
    '615' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-PB',  'Tribunal Regional Eleitoral do Estado da Paraíba'  ),
    '616' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-PR',  'Tribunal Regional Eleitoral do Estado de Pernambuco'  ),
    '617' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-PE',  'Tribunal Regional Eleitoral do Estado do Piauí'  ),
    '618' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-PI',  'Tribunal Regional Eleitoral do Estado do Paraná'  ),
    '619' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-RJ',  'Tribunal Regional Eleitoral do Estado do Rio de Janeiro'  ),
    '620' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-RN',  'Tribunal Regional Eleitoral do Estado do Rio Grande do Norte'  ),
    '621' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-RS',  'Tribunal Regional Eleitoral do Estado de Rondônia'  ),
    '622' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-RO',  'Tribunal Regional Eleitoral do Estado de Roraima'  ),
    '623' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-RR',  'Tribunal Regional Eleitoral do Estado do Rio Grande do Sul'  ),
    '624' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-SC',  'Tribunal Regional Eleitoral do Estado de Santa Catarina'  ),
    '625' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-SE',  'Tribunal Regional Eleitoral do Estado de Sergipe'  ),
    '626' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-SP',  'Tribunal Regional Eleitoral do Estado de São Paulo'  ),
    '627' : ( '6',  'Justiça Eleitoral',  'TRE',  'TRE-TO',  'Tribunal Regional Eleitoral do Estado de Tocantins'  ),
    '700' : ( '7',  'Justiça Militar da União',  'STM',  'STM',  'Superior Tribunal Militar'  ),
    '701' : ( '7',  'Justiça Militar da União',  'STM',  '1a CJM',  '1ª Circunscrição Judiciária Militar'  ),
    '702' : ( '7',  'Justiça Militar da União',  'STM',  '2a CJM',  '2ª Circunscrição Judiciária Militar'  ),
    '703' : ( '7',  'Justiça Militar da União',  'STM',  '3a CJM',  '3ª Circunscrição Judiciária Militar'  ),
    '704' : ( '7',  'Justiça Militar da União',  'STM',  '4a CJM',  '4ª Circunscrição Judiciária Militar'  ),
    '705' : ( '7',  'Justiça Militar da União',  'STM',  '5a CJM',  '5ª Circunscrição Judiciária Militar'  ),
    '706' : ( '7',  'Justiça Militar da União',  'STM',  '6a CJM',  '6ª Circunscrição Judiciária Militar'  ),
    '707' : ( '7',  'Justiça Militar da União',  'STM',  '7a CJM',  '7ª Circunscrição Judiciária Militar'  ),
    '708' : ( '7',  'Justiça Militar da União',  'STM',  '8a CJM',  '8ª Circunscrição Judiciária Militar'  ),
    '709' : ( '7',  'Justiça Militar da União',  'STM',  '9a CJM',  '9ª Circunscrição Judiciária Militar'  ),
    '710' : ( '7',  'Justiça Militar da União',  'STM',  '10a CJM',  '10ª Circunscrição Judiciária Militar'  ),
    '711' : ( '7',  'Justiça Militar da União',  'STM',  '11a CJM',  '11ª Circunscrição Judiciária Militar'  ),
    '712' : ( '7',  'Justiça Militar da União',  'STM',  '12a CJM',  '12ª Circunscrição Judiciária Militar'  ),
    '801' : ( '8',  'Justiça Estadual',  'TJ',  'TJAC',  'Tribunal de Justiça do Estado do Acre'  ),
    '802' : ( '8',  'Justiça Estadual',  'TJ',  'TJAL',  'Tribunal de Justiça do Estado de Alagoas'  ),
    '803' : ( '8',  'Justiça Estadual',  'TJ',  'TJAP',  'Tribunal de Justiça do Estado do Amazonas'  ),
    '804' : ( '8',  'Justiça Estadual',  'TJ',  'TJAM',  'Tribunal de Justiça do Estado do Amapá'  ),
    '805' : ( '8',  'Justiça Estadual',  'TJ',  'TJBA',  'Tribunal de Justiça do Estado da Bahia'  ),
    '806' : ( '8',  'Justiça Estadual',  'TJ',  'TJCE',  'Tribunal de Justiça do Estado do Ceará'  ),
    '807' : ( '8',  'Justiça Estadual',  'TJ',  'TJDFT',  'Tribunal de Justiça do Distrito Federal e dos Territórios'  ),
    '808' : ( '8',  'Justiça Estadual',  'TJ',  'TJES',  'Tribunal de Justiça do Estado do Espírito Santo'  ),
    '809' : ( '8',  'Justiça Estadual',  'TJ',  'TJGO',  'Tribunal de Justiça do Estado de Goiás'  ),
    '810' : ( '8',  'Justiça Estadual',  'TJ',  'TJMA',  'Tribunal de Justiça do Estado do Maranhão'  ),
    '811' : ( '8',  'Justiça Estadual',  'TJ',  'TJMT',  'Tribunal de Justiça do Estado de Minas Gerais'  ),
    '812' : ( '8',  'Justiça Estadual',  'TJ',  'TJMS',  'Tribunal de Justiça do Estado de Mato Grosso do Sul'  ),
    '813' : ( '8',  'Justiça Estadual',  'TJ',  'TJMG',  'Tribunal de Justiça do Estado de Mato Grosso'  ),
    '814' : ( '8',  'Justiça Estadual',  'TJ',  'TJPA',  'Tribunal de Justiça do Estado do Pará'  ),
    '815' : ( '8',  'Justiça Estadual',  'TJ',  'TJPB',  'Tribunal de Justiça do Estado da Paraíba'  ),
    '816' : ( '8',  'Justiça Estadual',  'TJ',  'TJPR',  'Tribunal de Justiça do Estado de Pernambuco'  ),
    '817' : ( '8',  'Justiça Estadual',  'TJ',  'TJPE',  'Tribunal de Justiça do Estado do Piauí'  ),
    '818' : ( '8',  'Justiça Estadual',  'TJ',  'TJPI',  'Tribunal de Justiça do Estado do Paraná'  ),
    '819' : ( '8',  'Justiça Estadual',  'TJ',  'TJRJ',  'Tribunal de Justiça do Estado do Rio de Janeiro'  ),
    '820' : ( '8',  'Justiça Estadual',  'TJ',  'TJRN',  'Tribunal de Justiça do Estado do Rio Grande do Norte'  ),
    '821' : ( '8',  'Justiça Estadual',  'TJ',  'TJRS',  'Tribunal de Justiça do Estado de Rondônia'  ),
    '822' : ( '8',  'Justiça Estadual',  'TJ',  'TJRO',  'Tribunal de Justiça do Estado de Roraima'  ),
    '823' : ( '8',  'Justiça Estadual',  'TJ',  'TJRR',  'Tribunal de Justiça do Estado do Rio Grande do Sul'  ),
    '824' : ( '8',  'Justiça Estadual',  'TJ',  'TJSC',  'Tribunal de Justiça do Estado de Santa Catarina'  ),
    '825' : ( '8',  'Justiça Estadual',  'TJ',  'TJSE',  'Tribunal de Justiça do Estado de Sergipe'  ),
    '826' : ( '8',  'Justiça Estadual',  'TJ',  'TJSP',  'Tribunal de Justiça do Estado de São Paulo'  ),
    '827' : ( '8',  'Justiça Estadual',  'TJ',  'TJTO',  'Tribunal de Justiça do Estado de Tocantins'  ),
    '913' : ( '9',  'Justiça Militar Estadual',  'TJM',  'TJMMG',  'Tribunal de Justiça Militar do Estado de Minas Gerais'  ),
    '921' : ( '9',  'Justiça Militar Estadual',  'TJM',  'TJMRS',  'Tribunal de Justiça Militar do Estado do Rio Grande do Sul'  ),
    '926' : ( '9',  'Justiça Militar Estadual',  'TJM',  'TJMSP',  'Tribunal de Justiça Militar do Estado de São Paulo'  ),
}