#   KEY                 [0]         [1]                  [2]          [3]
#  Sigla Tribunal  :   seq_cnj   nome_ramo_justica    ramo_justica    UF

dic_tribunal_ramo_uf = {
    'STF' : ( '1',  'Supremo Tribunal Federal',  'STF',  ''  ),
    'CNJ' : ( '2',  'Conselho Nacional de Justiça',  'CNJ',  ''  ),
    'STJ' : ( '3',  'Superior Tribunal de Justiça',  'STJ',  ''  ),
    'TRF' : ( '4',  'Justiça Federal',  'TRF',  ''  ),
    'TRF1' : ( '4',  'Justiça Federal',  'TRF',  ''  ),
    'TRF2' : ( '4',  'Justiça Federal',  'TRF',  ''  ),
    'TRF3' : ( '4',  'Justiça Federal',  'TRF',  ''  ),
    'TRF4' : ( '4',  'Justiça Federal',  'TRF',  ''  ),
    'TRF5' : ( '4',  'Justiça Federal',  'TRF',  ''  ),
    'TST' : ( '5',  'Justiça do Trabalho',  'TRT',  ''  ),
    'TRT1' : ( '5',  'Justiça do Trabalho',  'TRT',  'RJ'  ),
    'TRT2' : ( '5',  'Justiça do Trabalho',  'TRT',  'SP'  ),
    'TRT3' : ( '5',  'Justiça do Trabalho',  'TRT',  'MG'  ),
    'TRT4' : ( '5',  'Justiça do Trabalho',  'TRT',  'RS'  ),
    'TRT5' : ( '5',  'Justiça do Trabalho',  'TRT',  'BA'  ),
    'TRT6' : ( '5',  'Justiça do Trabalho',  'TRT',  'PE'  ),
    'TRT7' : ( '5',  'Justiça do Trabalho',  'TRT',  'CE'  ),
    'TRT8' : ( '5',  'Justiça do Trabalho',  'TRT',  'PA'  ),
    'TRT9' : ( '5',  'Justiça do Trabalho',  'TRT',  'PR'  ),
    'TRT10' : ( '5',  'Justiça do Trabalho',  'TRT',  'DF'  ),
    'TRT11' : ( '5',  'Justiça do Trabalho',  'TRT',  'AM'  ),
    'TRT12' : ( '5',  'Justiça do Trabalho',  'TRT',  'SC'  ),
    'TRT13' : ( '5',  'Justiça do Trabalho',  'TRT',  'PB'  ),
    'TRT14' : ( '5',  'Justiça do Trabalho',  'TRT',  'AC'  ),
    'TRT15' : ( '5',  'Justiça do Trabalho',  'TRT',  'SP'  ),
    'TRT16' : ( '5',  'Justiça do Trabalho',  'TRT',  'MA'  ),
    'TRT17' : ( '5',  'Justiça do Trabalho',  'TRT',  'ES'  ),
    'TRT18' : ( '5',  'Justiça do Trabalho',  'TRT',  'GO'  ),
    'TRT19' : ( '5',  'Justiça do Trabalho',  'TRT',  'AL'  ),
    'TRT20' : ( '5',  'Justiça do Trabalho',  'TRT',  'SE'  ),
    'TRT21' : ( '5',  'Justiça do Trabalho',  'TRT',  'RN'  ),
    'TRT22' : ( '5',  'Justiça do Trabalho',  'TRT',  'PI'  ),
    'TRT23' : ( '5',  'Justiça do Trabalho',  'TRT',  'MT'  ),
    'TRT24' : ( '5',  'Justiça do Trabalho',  'TRT',  'MS'  ),
    'CSJT' : ( '5',  'Justiça do Trabalho',  'TRT',  ''  ),
    'TRE-AC' : ( '6',  'Justiça Eleitoral',  'TRE',  'AC'  ),
    'TRE-AL' : ( '6',  'Justiça Eleitoral',  'TRE',  'AL'  ),
    'TRE-AP' : ( '6',  'Justiça Eleitoral',  'TRE',  'AP'  ),
    'TRE-AM' : ( '6',  'Justiça Eleitoral',  'TRE',  'AM'  ),
    'TRE-BA' : ( '6',  'Justiça Eleitoral',  'TRE',  'BA'  ),
    'TRE-CE' : ( '6',  'Justiça Eleitoral',  'TRE',  'CE'  ),
    'TRE-DF' : ( '6',  'Justiça Eleitoral',  'TRE',  'DF'  ),
    'TRE-ES' : ( '6',  'Justiça Eleitoral',  'TRE',  'ES'  ),
    'TRE-GO' : ( '6',  'Justiça Eleitoral',  'TRE',  'GO'  ),
    'TRE-MA' : ( '6',  'Justiça Eleitoral',  'TRE',  'MA'  ),
    'TRE-MT' : ( '6',  'Justiça Eleitoral',  'TRE',  'MT'  ),
    'TRE-MS' : ( '6',  'Justiça Eleitoral',  'TRE',  'MS'  ),
    'TRE-MG' : ( '6',  'Justiça Eleitoral',  'TRE',  'MG'  ),
    'TRE-PA' : ( '6',  'Justiça Eleitoral',  'TRE',  'PA'  ),
    'TRE-PB' : ( '6',  'Justiça Eleitoral',  'TRE',  'PB'  ),
    'TRE-PR' : ( '6',  'Justiça Eleitoral',  'TRE',  'PR'  ),
    'TRE-PE' : ( '6',  'Justiça Eleitoral',  'TRE',  'PE'  ),
    'TRE-PI' : ( '6',  'Justiça Eleitoral',  'TRE',  'PI'  ),
    'TRE-RJ' : ( '6',  'Justiça Eleitoral',  'TRE',  'RJ'  ),
    'TRE-RN' : ( '6',  'Justiça Eleitoral',  'TRE',  'RN'  ),
    'TRE-RS' : ( '6',  'Justiça Eleitoral',  'TRE',  'RS'  ),
    'TRE-RO' : ( '6',  'Justiça Eleitoral',  'TRE',  'RO'  ),
    'TRE-RR' : ( '6',  'Justiça Eleitoral',  'TRE',  'RR'  ),
    'TRE-SC' : ( '6',  'Justiça Eleitoral',  'TRE',  'SC'  ),
    'TRE-SE' : ( '6',  'Justiça Eleitoral',  'TRE',  'SE'  ),
    'TRE-SP' : ( '6',  'Justiça Eleitoral',  'TRE',  'SP'  ),
    'TRE-TO' : ( '6',  'Justiça Eleitoral',  'TRE',  'TO'  ),
    'STM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '1a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '2a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '3a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '4a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '5a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '6a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '7a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '8a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '9a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '10a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '11a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    '12a CJM' : ( '7',  'Justiça Militar da União',  'STM',  ''  ),
    'TJAC' : ( '8',  'Justiça Estadual',  'TJ',  'AC'  ),
    'TJAL' : ( '8',  'Justiça Estadual',  'TJ',  'AL'  ),
    'TJAP' : ( '8',  'Justiça Estadual',  'TJ',  'AP'  ),
    'TJAM' : ( '8',  'Justiça Estadual',  'TJ',  'AM'  ),
    'TJBA' : ( '8',  'Justiça Estadual',  'TJ',  'BA'  ),
    'TJCE' : ( '8',  'Justiça Estadual',  'TJ',  'CE'  ),
    'TJDFT' : ( '8',  'Justiça Estadual',  'TJ',  'FT'  ),
    'TJES' : ( '8',  'Justiça Estadual',  'TJ',  'ES'  ),
    'TJGO' : ( '8',  'Justiça Estadual',  'TJ',  'GO'  ),
    'TJMA' : ( '8',  'Justiça Estadual',  'TJ',  'MA'  ),
    'TJMT' : ( '8',  'Justiça Estadual',  'TJ',  'MT'  ),
    'TJMS' : ( '8',  'Justiça Estadual',  'TJ',  'MS'  ),
    'TJMG' : ( '8',  'Justiça Estadual',  'TJ',  'MG'  ),
    'TJPA' : ( '8',  'Justiça Estadual',  'TJ',  'PA'  ),
    'TJPB' : ( '8',  'Justiça Estadual',  'TJ',  'PB'  ),
    'TJPR' : ( '8',  'Justiça Estadual',  'TJ',  'PR'  ),
    'TJPE' : ( '8',  'Justiça Estadual',  'TJ',  'PE'  ),
    'TJPI' : ( '8',  'Justiça Estadual',  'TJ',  'PI'  ),
    'TJRJ' : ( '8',  'Justiça Estadual',  'TJ',  'RJ'  ),
    'TJRN' : ( '8',  'Justiça Estadual',  'TJ',  'RN'  ),
    'TJRS' : ( '8',  'Justiça Estadual',  'TJ',  'RS'  ),
    'TJRO' : ( '8',  'Justiça Estadual',  'TJ',  'RO'  ),
    'TJRR' : ( '8',  'Justiça Estadual',  'TJ',  'RR'  ),
    'TJSC' : ( '8',  'Justiça Estadual',  'TJ',  'SC'  ),
    'TJSE' : ( '8',  'Justiça Estadual',  'TJ',  'SE'  ),
    'TJSP' : ( '8',  'Justiça Estadual',  'TJ',  'SP'  ),
    'TJTO' : ( '8',  'Justiça Estadual',  'TJ',  'TO'  ),
    'TJMMG' : ( '9',  'Justiça Militar Estadual',  'TJM',  'MG'  ),
    'TJMRS' : ( '9',  'Justiça Militar Estadual',  'TJM',  'RS'  ),
    'TJMSP' : ( '9',  'Justiça Militar Estadual',  'TJM',  'SP'  ),
}