
#  KEY                            [0]                  [1]
#  sigla_tribunal ou UF  :     ramo_justica ou UF      descricao

dic_tribunal = {
    'todos' : ( 'todos',  'Todos Tribunais do Brasil'  ),
    'STF' : ( 'STF',  'Supremo Tribunal Federal'  ),
    'CNJ' : ( 'CNJ',  'Conselho Nacional de Justiça'  ),
    'STJ' : ( 'STJ',  'Superior Tribunal de Justiça'  ),
    'TRF' : ( 'TRF',  'Justiça Federal'  ),
    'TRF1' : ( 'TRF',  'TRF da 1a Região'  ),
    'TRF2' : ( 'TRF',  'TRF da 2a Região'  ),
    'TRF3' : ( 'TRF',  'TRF da 3a Região'  ),
    'TRF4' : ( 'TRF',  'TRF da 4a Região'  ),
    'TRF5' : ( 'TRF',  'TRF da 5a Região'  ),
    'TRT' : ( 'TRT',  'Justiça do Trabalho'  ),
    'TST' : ( 'TRT',  'Tribunal Superior do Trabalho'  ),
    'TRT1' : ( 'TRT',  'Tribunal Regional do Trabalho da 1ª Região'  ),
    'TRT2' : ( 'TRT',  'Tribunal Regional do Trabalho da 2ª Região'  ),
    'TRT3' : ( 'TRT',  'Tribunal Regional do Trabalho da 3ª Região'  ),
    'TRT4' : ( 'TRT',  'Tribunal Regional do Trabalho da 4ª Região'  ),
    'TRT5' : ( 'TRT',  'Tribunal Regional do Trabalho da 5ª Região'  ),
    'TRT6' : ( 'TRT',  'Tribunal Regional do Trabalho da 6ª Região'  ),
    'TRT7' : ( 'TRT',  'Tribunal Regional do Trabalho da 7ª Região'  ),
    'TRT8' : ( 'TRT',  'Tribunal Regional do Trabalho da 8ª Região'  ),
    'TRT9' : ( 'TRT',  'Tribunal Regional do Trabalho da 9ª Região'  ),
    'TRT10' : ( 'TRT',  'Tribunal Regional do Trabalho da 10ª Região'  ),
    'TRT11' : ( 'TRT',  'Tribunal Regional do Trabalho da 11ª Região'  ),
    'TRT12' : ( 'TRT',  'Tribunal Regional do Trabalho da 12ª Região'  ),
    'TRT13' : ( 'TRT',  'Tribunal Regional do Trabalho da 13ª Região'  ),
    'TRT14' : ( 'TRT',  'Tribunal Regional do Trabalho da 14ª Região'  ),
    'TRT15' : ( 'TRT',  'Tribunal Regional do Trabalho da 15ª Região'  ),
    'TRT16' : ( 'TRT',  'Tribunal Regional do Trabalho da 16ª Região'  ),
    'TRT17' : ( 'TRT',  'Tribunal Regional do Trabalho da 17ª Região'  ),
    'TRT18' : ( 'TRT',  'Tribunal Regional do Trabalho da 18ª Região'  ),
    'TRT19' : ( 'TRT',  'Tribunal Regional do Trabalho da 19ª Região'  ),
    'TRT20' : ( 'TRT',  'Tribunal Regional do Trabalho da 20ª Região'  ),
    'TRT21' : ( 'TRT',  'Tribunal Regional do Trabalho da 21ª Região'  ),
    'TRT22' : ( 'TRT',  'Tribunal Regional do Trabalho da 22ª Região'  ),
    'TRT23' : ( 'TRT',  'Tribunal Regional do Trabalho da 23ª Região'  ),
    'TRT24' : ( 'TRT',  'Tribunal Regional do Trabalho da 24ª Região'  ),
    'CSJT' : ( 'TRT',  'Conselho Superior da Justiça do Trabalho'  ),
    'TRE' : ( 'TRE',  'Justiça Eleitoral'  ),
    'TRE-AC' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Acre'  ),
    'TRE-AL' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Alagoas'  ),
    'TRE-AP' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Amazonas'  ),
    'TRE-AM' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Amapá'  ),
    'TRE-BA' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado da Bahia'  ),
    'TRE-CE' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Ceará'  ),
    'TRE-DF' : ( 'TRE',  'Tribunal Regional Eleitoral do Distrito Federal '  ),
    'TRE-ES' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Espírito Santo'  ),
    'TRE-GO' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Goiás'  ),
    'TRE-MA' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Maranhão'  ),
    'TRE-MT' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Minas Gerais'  ),
    'TRE-MS' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Mato Grosso do Sul'  ),
    'TRE-MG' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Mato Grosso'  ),
    'TRE-PA' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Pará'  ),
    'TRE-PB' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado da Paraíba'  ),
    'TRE-PR' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Pernambuco'  ),
    'TRE-PE' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Piauí'  ),
    'TRE-PI' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Paraná'  ),
    'TRE-RJ' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Rio de Janeiro'  ),
    'TRE-RN' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Rio Grande do Norte'  ),
    'TRE-RS' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Rondônia'  ),
    'TRE-RO' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Roraima'  ),
    'TRE-RR' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado do Rio Grande do Sul'  ),
    'TRE-SC' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Santa Catarina'  ),
    'TRE-SE' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Sergipe'  ),
    'TRE-SP' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de São Paulo'  ),
    'TRE-TO' : ( 'TRE',  'Tribunal Regional Eleitoral do Estado de Tocantins'  ),
    'STM' : ( 'STM',  'Superior Tribunal Militar'  ),
    '1a CJM' : ( 'STM',  '1ª Circunscrição Judiciária Militar'  ),
    '2a CJM' : ( 'STM',  '2ª Circunscrição Judiciária Militar'  ),
    '3a CJM' : ( 'STM',  '3ª Circunscrição Judiciária Militar'  ),
    '4a CJM' : ( 'STM',  '4ª Circunscrição Judiciária Militar'  ),
    '5a CJM' : ( 'STM',  '5ª Circunscrição Judiciária Militar'  ),
    '6a CJM' : ( 'STM',  '6ª Circunscrição Judiciária Militar'  ),
    '7a CJM' : ( 'STM',  '7ª Circunscrição Judiciária Militar'  ),
    '8a CJM' : ( 'STM',  '8ª Circunscrição Judiciária Militar'  ),
    '9a CJM' : ( 'STM',  '9ª Circunscrição Judiciária Militar'  ),
    '10a CJM' : ( 'STM',  '10ª Circunscrição Judiciária Militar'  ),
    '11a CJM' : ( 'STM',  '11ª Circunscrição Judiciária Militar'  ),
    '12a CJM' : ( 'STM',  '12ª Circunscrição Judiciária Militar'  ),
    'TJ' : ( 'TJ',  'Justiça Estadual'  ),
    'TJAC' : ( 'TJ',  'Tribunal de Justiça do Estado do Acre'  ),
    'TJAL' : ( 'TJ',  'Tribunal de Justiça do Estado de Alagoas'  ),
    'TJAP' : ( 'TJ',  'Tribunal de Justiça do Estado do Amazonas'  ),
    'TJAM' : ( 'TJ',  'Tribunal de Justiça do Estado do Amapá'  ),
    'TJBA' : ( 'TJ',  'Tribunal de Justiça do Estado da Bahia'  ),
    'TJCE' : ( 'TJ',  'Tribunal de Justiça do Estado do Ceará'  ),
    'TJDFT' : ( 'TJ',  'Tribunal de Justiça do Distrito Federal e dos Territórios'  ),
    'TJES' : ( 'TJ',  'Tribunal de Justiça do Estado do Espírito Santo'  ),
    'TJGO' : ( 'TJ',  'Tribunal de Justiça do Estado de Goiás'  ),
    'TJMA' : ( 'TJ',  'Tribunal de Justiça do Estado do Maranhão'  ),
    'TJMT' : ( 'TJ',  'Tribunal de Justiça do Estado de Minas Gerais'  ),
    'TJMS' : ( 'TJ',  'Tribunal de Justiça do Estado de Mato Grosso do Sul'  ),
    'TJMG' : ( 'TJ',  'Tribunal de Justiça do Estado de Mato Grosso'  ),
    'TJPA' : ( 'TJ',  'Tribunal de Justiça do Estado do Pará'  ),
    'TJPB' : ( 'TJ',  'Tribunal de Justiça do Estado da Paraíba'  ),
    'TJPR' : ( 'TJ',  'Tribunal de Justiça do Estado de Pernambuco'  ),
    'TJPE' : ( 'TJ',  'Tribunal de Justiça do Estado do Piauí'  ),
    'TJPI' : ( 'TJ',  'Tribunal de Justiça do Estado do Paraná'  ),
    'TJRJ' : ( 'TJ',  'Tribunal de Justiça do Estado do Rio de Janeiro'  ),
    'TJRN' : ( 'TJ',  'Tribunal de Justiça do Estado do Rio Grande do Norte'  ),
    'TJRS' : ( 'TJ',  'Tribunal de Justiça do Estado de Rondônia'  ),
    'TJRO' : ( 'TJ',  'Tribunal de Justiça do Estado de Roraima'  ),
    'TJRR' : ( 'TJ',  'Tribunal de Justiça do Estado do Rio Grande do Sul'  ),
    'TJSC' : ( 'TJ',  'Tribunal de Justiça do Estado de Santa Catarina'  ),
    'TJSE' : ( 'TJ',  'Tribunal de Justiça do Estado de Sergipe'  ),
    'TJSP' : ( 'TJ',  'Tribunal de Justiça do Estado de São Paulo'  ),
    'TJTO' : ( 'TJ',  'Tribunal de Justiça do Estado de Tocantins'  ),
    'TJM' : ( 'TJM',  'Justiça Militar Estadual'  ),
    'TJMMG' : ( 'TJM',  'Tribunal de Justiça Militar do Estado de Minas Gerais'  ),
    'TJMRS' : ( 'TJM',  'Tribunal de Justiça Militar do Estado do Rio Grande do Sul'  ),
    'TJMSP' : ( 'TJM',  'Tribunal de Justiça Militar do Estado de São Paulo'  ),
}